name: Deploy to VPS

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Sync files to server via rsync over SSH
      uses: burnett01/rsync-deployments@v5.2
      with:
        switches: -avzr --delete
        path: ./
        remote_path: /var/www/s7v.ru/html/
        remote_host: 91.107.126.237
        remote_user: root
        remote_key: ${{ secrets.VPS_SSH_KEY }}
