name: Deploy to VPS1

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy files via SCP
        uses: appleboy/scp-action@v0.1.4
        with:
          host: 91.107.126.237
          username: root
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          source: "./"
          target: "/var/www/s7v.ru/html/"
